### ISSUE TITLE
cannot import name 'BacktestAsset' from 'hftbacktest'

### ISSUE THREAD

**Issue by isslerman** [nkaz001/hftbacktest#111]
I am trying to do some examples from the documentation, but not sure if this still work.

From the Getting Started page: https://hftbacktest.readthedocs.io/en/latest/tutorials/Getting%20Started.html

from hftbacktest import BacktestAsset, HashMapMarketDepthBacktest

generates an error:

ImportError: cannot import name 'BacktestAsset' from 'hftbacktest' (/opt/anaconda3/envs/hft/lib/python3.12/site-packages/hftbacktest/__init__.py)

Tks 
Marcos Issler

**Comment by ian-wazowski** [comment]
Major code refactoring is currently underway. Since the examples/ code is still undergoing numerous changes, please directly verify the function signatures yourself.

**Comment by nkaz001** [comment]
Which version are you using? Does it happen in 2.0.0rc0?

**Comment by isslerman** [comment]
Using 1.8.4 with conda. I will check the 2.0.0rc0.

**Comment by isslerman** [comment]
Works fine with > 2.0.0rc0
